# Generated by Django 6.1.1 on 2026-09-12 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_reference", models.CharField(max_length=20, unique=True)),
                (
                    "student_age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(21),
                        ]
                    ),
                ),
                ("parent_email", models.EmailField(max_length=254)),
                ("region", models.CharField(max_length=30)),
                ("has_learning_difficulty", models.BooleanField()),
                ("requires_lsa_support", models.BooleanField()),
                ("consent_to_process_data", models.BooleanField()),
                ("requires_transport_support", models.BooleanField()),
                ("requires_medical_assistance", models.BooleanField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_onboarding",
            },
        ),
    ]
